coursework/coursework/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),            # Головна сторінка та інформаційні сторінки
    path('users/', include('users.urls')),      # Сторінки для користувачів
    path('finance/', include('finance.urls')),  # Фінансові сторінки
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursework/pages/urls.py
from django.urls import path
from . import views 


urlpatterns = [
    path('', views.main, name='main'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('documents/<int:document_id>/', views.documents, name='documents'),
]

coursework/users/urls.py
from django.urls import path
from . import views 

app_name = 'users'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_in/', views.log_in, name='log_in'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('log_out/', views.logout_user, name='logout_user'),
]

coursework/users/models.py
from django.db import models
from django.contrib.auth.models import User
from pages.models import Currency

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, blank=False, null=False)
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True)
    photo = models.ImageField(upload_to='profile_photos', blank=True, null=True)
    encrypted_password = models.BinaryField(blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'Профіль користувача'
        verbose_name_plural = 'Профілі користувачів'

    

coursework/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile
from pages.models import Currency
import re
from users.encryption_util import load_key, encrypt_data, decrypt_data


class UserRegistrationForm(UserCreationForm):
    full_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'fullName'}),
        error_messages={'required': 'Це поле обов\'язкове.'}
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'id': 'email'}),
        error_messages={'required': 'Це поле обов\'язкове.', 'invalid': 'Введіть коректну електронну пошту (повинні бути символи @ та .).'}
    )
    currency = forms.ModelChoiceField(
        queryset=Currency.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-select', 'id': 'currency'}),
        error_messages={'required': 'Це поле обов\'язкове.'}
    )
    photo = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control', 'id': 'photo', 'accept': 'image/*', 'onchange': 'previewPhoto()'})
    )
    password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password1'}),
        error_messages={'required': 'Це поле обов\'язкове.'}
    )
    password2 = forms.CharField(
        label="Підтвердження пароля",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password2'}),
        error_messages={'required': 'Це поле обов\'язкове.'}
    )

    class Meta:
        model = User
        fields = ['username', 'full_name', 'email', 'currency', 'photo', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'id': 'login'})
        }
        error_messages = {
            'username': {'required': 'Це поле обов\'язкове.'}
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Ця адреса електронної пошти вже використовується.')
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not re.match(r'^[a-zA-Z0-9_-]+$', username):
            raise forms.ValidationError('Логін може містити тільки англійські літери, цифри та символи _ або -.')
        return username
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            raise forms.ValidationError('Пароль повинен містити щонайменше 8 символів.')
        if not re.search(r'[A-Za-z]', password1):
            raise forms.ValidationError('Пароль повинен містити хоча б одну літеру.')
        if not re.search(r'\d', password1):
            raise forms.ValidationError('Пароль повинен містити хоча б одну цифру.')
        if not re.search(r'[@$!%*?&]', password1):
            raise forms.ValidationError('Пароль повинен містити хоча б один спеціальний символ (@$!%*?&).')
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Паролі не співпадають.')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            key = load_key('users/encryption_key.key')
            encrypted_password = encrypt_data(self.cleaned_data['password1'], key)
            Profile.objects.create(
                user=user,
                full_name=self.cleaned_data['full_name'],
                currency=self.cleaned_data['currency'],
                photo=self.cleaned_data.get('photo'),
                encrypted_password=encrypted_password
            )
        return user
    

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'login',
            'required': True
        }),
        error_messages={'required': 'Це поле обов\'язкове.'}
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'id': 'password',
            'required': True
        }),
        error_messages={'required': 'Це поле обов\'язкове.'}
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("Даного логіну не існує")
        return username

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            try:
                user = User.objects.get(username=username)
                profile = Profile.objects.get(user=user)
                key = load_key('users/encryption_key.key')
                decrypted_password = decrypt_data(profile.encrypted_password, key)
                
                if password != decrypted_password:
                    self.add_error('password', "Неправильний пароль")
            except User.DoesNotExist:
                raise forms.ValidationError("Даного логіну не існує")
            except Profile.DoesNotExist:
                raise forms.ValidationError("Профіль не знайдено")

        return cleaned_data



class ProfileForm(forms.ModelForm):
    username = forms.CharField(
        max_length=150,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'username'})
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'id': 'email'})
    )
    password1 = forms.CharField(
        label="Новий пароль",
        required=False,
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password1'})
    )
    password2 = forms.CharField(
        label="Підтвердження пароля",
        required=False,
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password2'})
    )

    class Meta:
        model = Profile
        fields = ['full_name', 'currency', 'photo', 'username', 'email', 'password1', 'password2']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'id': 'fullName'}),
            'currency': forms.Select(attrs={'class': 'form-select', 'id': 'currency'}),
            'photo': forms.FileInput(attrs={'class': 'form-control', 'id': 'photo', 'accept': 'image/*', 'onchange': 'previewPhoto()'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields['username'].initial = self.user.username
            self.fields['email'].initial = self.user.email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exclude(pk=self.user.pk).exists():
            raise forms.ValidationError('username', "Користувач з таким логіном вже існує.")
        return username


    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password1 != password2:
            self.add_error('password2', "Паролі не співпадають")

        return cleaned_data

    def save(self, commit=True):
        profile = super().save(commit=False)
        user = profile.user
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        if self.cleaned_data['password1']:
            key = load_key('users/encryption_key.key')
            encrypted_password = encrypt_data(self.cleaned_data['password1'], key)
            profile.encrypted_password = encrypted_password
            user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
            profile.save()
        return profile

coursework/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import UserRegistrationForm, CustomAuthenticationForm, ProfileForm

# Create your views here.
def sign_up(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Реєстрація пройшла успішно!')
            return redirect('finance:accounts')
        else:
            messages.error(request, 'Будь ласка, виправте помилки у формі.')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/sign_up.html', {'form': form})

def log_in(request):
    error_message = None
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('finance:accounts')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'users/log_in.html', {'form': form})


@login_required
def view_profile(request):
    profile = request.user.profile
    return render(request, 'users/view_profile.html', {'profile': profile})

@login_required
def edit_profile(request):
    profile = request.user.profile
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Профіль успішно оновлено.')
            return redirect('users:view_profile')
    else:
        form = ProfileForm(instance=profile, user=request.user)
    return render(request, 'users/edit_profile.html', {'form': form, 'profile': profile})

@login_required
def logout_user(request):
    logout(request)
    return redirect('users:log_in')

coursework/users/templates/users/edit_profile.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Редагування профілю{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/sign_up/sign_up_form.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/sign_up/photo.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/sign_up/photo-upload.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/sign_up/photo_size.css' %}" rel="stylesheet">
  <script src="{% static 'users/js/edit_profile/edit_profile.js' %}"></script>
{% endblock %}

{% block profile_active %}active{% endblock %}

{% block profile_disabled %}disabled{% endblock %}

{% block content %}
  <div class="container mt-5 main-content"> 
    <h2 class="mb-3">Редагувати профіль</h2>
    <div class="row">
      <form method="POST" novalidate enctype="multipart/form-data">
        <div class="registration-container d-flex flex-column flex-sm-row">
          {% csrf_token %}
          <div class="photo-upload mb-3 col-md-4 d-flex flex-column align-items-center">
            {% if profile.photo %}
              <img id="photoPreview" class="photo-preview mb-3" src="{{ profile.photo.url }}" alt="Photo Preview" style="display: block;">
            {% else %}
              <i class="bi bi-camera icon"></i>
              <img id="photoPreview" class="photo-preview mb-3" src="" alt="Photo Preview" style="display: none;">
            {% endif %}
            {{ form.photo }}
          </div>
          <div class="form-container col-md-8">
            <div class="mb-3">
              <label for="fullName" class="form-label">Повне Ім'я</label>
              {{ form.full_name }}
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Електронна пошта</label>
              {{ form.email }}
            </div>
            <div class="mb-3">
              <label for="username" class="form-label">Логін</label>
              {{ form.username }}
            </div>
            <div class="mb-3">
              <label for="password1" class="form-label">Новий пароль</label>
              {{ form.password1 }}
            </div>
            <div class="mb-3">
              <label for="password2" class="form-label">Підтвердження пароля</label>
              {{ form.password2 }}
            </div>
            <div class="mb-3">
              <label for="currency" class="form-label">Валюта</label>
              {{ form.currency }}
            </div>
          </div> 
        </div>
        <div class="text-center mt-1 mt-md-3 mb-4 mb-md-5">
          <button type="submit" class="btn btn-primary">Зберегти зміни</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

coursework/users/templates/users/log_in.html
{% extends 'pages/loyout.html' %}
{% load static %}

{% block title %}Вхід в аккаунт{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/log_in/log_in.css' %}" rel="stylesheet">
{% endblock %}

{% block enter_active %}active{% endblock %}

{% block log_in_disabled %}disabled{% endblock %}

{% block content %}
  <div class="container my-5 main-content">
    <h2 class="mb-3 text-center">Форма входу</h2>
    <div class="row justify-content-center">
      <div class="col-md-7 col-lg-6 form-container">
        <form method="POST" novalidate>
          {% csrf_token %}
          <div class="mb-3">
            <label for="{{ form.username.id_for_label }}" class="form-label">Логін</label>
            {{ form.username }}
            {% for error in form.username.errors %}
              <div class="error-message">{{ error }}</div>
            {% endfor %}
          </div>
          <div class="mb-3">
            <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
            {{ form.password }}
            {% for error in form.password.errors %}
              <div class="error-message">{{ error }}</div>
            {% endfor %}
          </div>
          <div class="d-grid">
            <button type="submit" class="btn btn-primary">Увійти в аккаунт</button>
          </div>
          <div class="mt-3 centered-links">
            <div class="flex-item">
              <a href="{% url 'users:sign_up' %}">Зареєструватися</a>
            </div>
            <span class="divider">|</span>
            <div class="flex-item">
              <a href="#">Забули пароль?</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

coursework/users/templates/users/sign_up.html
{% extends 'pages/loyout.html' %}
{% load static %}

{% block title %}Реєстрація{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/sign_up/sign_up_form.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/sign_up/photo_size.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/sign_up/photo-upload.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/sign_up/photo.css' %}" rel="stylesheet">
  <script src="{% static 'pages/js/sign_up/photo.js' %}"></script>
{% endblock %}

{% block enter_active %}active{% endblock %}

{% block sign_up_disabled %}disabled{% endblock %}

{% block content %}
  <div class="container mt-5 main-content"> 
    <h2 class="mb-3">Форма реєстрації</h2>
    <div class="row">
      <form method="POST" novalidate>
        <div class="registration-container d-flex flex-column flex-sm-row">
          {% csrf_token %}
          <div class="photo-upload mb-3 col-md-4 d-flex flex-column align-items-center">
            <i class="bi bi-camera icon"></i>
            <img id="photoPreview" class="photo-preview mb-3" src="" alt="Photo Preview">
            {{ form.photo }}
          </div>
          <div class="form-container col-md-8">
            <div class="mb-3">
              <label for="fullName" class="form-label">Повне Ім'я</label>
              {{ form.full_name }}
              {% for error in form.full_name.errors %}
                <div class="text-danger">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Електронна пошта</label>
              {{ form.email }}
              {% for error in form.email.errors %}
                <div class="text-danger">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="mb-3">
              <label for="login" class="form-label">Логін</label>
              {{ form.username }}
              {% for error in form.username.errors %}
                <div class="text-danger">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="mb-3">
              <label for="currency" class="form-label">Валюта</label>
              {{ form.currency }}
              {% for error in form.currency.errors %}
                <div class="text-danger">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="mb-3">
              <label for="password1" class="form-label">Пароль</label>
              {{ form.password1 }}
              {% for error in form.password1.errors %}
                <div class="text-danger">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="mb-3">
              <label for="password2" class="form-label">Підтвердження пароля</label>
              {{ form.password2 }}
              {% for error in form.password2.errors %}
                <div class="text-danger">{{ error }}</div>
              {% endfor %}
            </div>
          </div> 
        </div>
        <div class="text-center mt-1 mt-md-3 mb-4 mb-md-5">
          <button type="submit" class="btn btn-primary">Зареєструватися</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

coursework/users/templates/users/view_profile.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Профіль користувача{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/sign_up/sign_up_form.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/sign_up/photo_size.css' %}" rel="stylesheet">
  <link href="{% static 'users/css/view_profile/password_icon.css' %}" rel="stylesheet">
  <link href="{% static 'users/css/view_profile/photo.css' %}" rel="stylesheet">
{% endblock %}

{% block profile_active %}active{% endblock %}

{% block profile_disabled %}disabled{% endblock %}

{% block content %}
  <div class="container mt-4 mt-sm-5 main-content">
    <h2 class="mb-3">Профіль користувача</h2>
    <div class="row">
      <div class="registration-container d-flex flex-column flex-sm-row">
        <div class="photo-upload">
          {% if profile.photo %}
            <img id="photoPreview" class="photo-preview" src="{{ profile.photo.url }}" alt="Photo Preview">
          {% else %}
            <i class="bi bi-camera icon"></i>
          {% endif %}
        </div>
        <div class="form-container col-12 col-sm-8">
          <div class="mb-3">
            <label for="fullName" class="form-label">Повне Ім'я</label>
            <input type="text" class="form-control" id="fullName" value="{{ profile.full_name }}" readonly>
          </div>
          <div class="mb-3">
            <label for="username" class="form-label">Логін</label>
            <input type="text" class="form-control" id="username" value="{{ profile.user.username }}" readonly>
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Електронна пошта</label>
            <input type="email" class="form-control" id="email" value="{{ profile.user.email }}" readonly>
          </div>
          <div class="mb-3">
            <label for="currency" class="form-label">Валюта</label>
            <input type="text" class="form-control" id="currency" value="{{ profile.currency.name }}" readonly>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center">
        <a href="{% url 'users:edit_profile' %}" class="btn btn-primary mt-1 mt-md-3 mb-4 mb-md-5">Редагувати профіль</a>
      </div>
    </div>
  </div>
{% endblock %}