coursework/coursework/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),            # Головна сторінка та інформаційні сторінки
    path('users/', include('users.urls')),      # Сторінки для користувачів
    path('finance/', include('finance.urls')),  # Фінансові сторінки
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursework/pages/urls.py
from django.urls import path
from . import views 


urlpatterns = [
    path('', views.main, name='main'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('documents/<int:document_id>/', views.documents, name='documents'),
]

coursework/users/urls.py
from django.urls import path
from . import views 

app_name = 'users'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_in/', views.log_in, name='log_in'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('log_out/', views.logout_user, name='logout_user'),
]

coursework/pages/templates/pages/about_us.html
{% extends 'pages/loyout.html' %}
{% load static %}

{% block title %}Про нас{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/general/blue-border_and_card.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/about_us/timeline_and_partner-logo.css' %}" rel="stylesheet">
{% endblock %}

{% block about_us_active %}active{% endblock %}

{% block content %}
  <div class="container-fluid header text-center py-5">
    <h1 class="display-4">Про нас</h1>
  </div>

  <div class="container mt-3 mt-md-5 mb-5">
    <div class="row">
      <div class="col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
        <div class="blue-border">
          <h2 class="text-center">Місія та мета компанії</h2>
          <p class="text-justify mt-1">
            У Finance Fusion наша місія полягає в тому, щоб надати користувачам потужні та зручні інструменти для
            управління своїми фінансами. Ми прагнемо допомогти людям ефективно контролювати свої доходи та витрати,
            планувати бюджет та приймати обґрунтовані фінансові рішення. За допомогою нашої платформи користувачі можуть
            легко відстежувати свої фінансові потоки, отримувати детальні звіти та аналізувати свої фінансові звички.
          </p>
          <p class="text-justify mb-0">
            Наша мета - забезпечити фінансову прозорість та покращити фінансову грамотність кожного користувача. Ми
            віримо, що знання та розуміння власних фінансів є ключем до фінансової стабільності та добробуту. Тому ми
            постійно працюємо над удосконаленням наших інструментів та сервісів, щоб забезпечити максимально зручний і
            ефективний досвід користування.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container mt-3 mt-md-5 mb-5">
    <h2 class="text-center mb-4">Історія компанії</h2>
    <div class="timeline-simple">
      <div class="timeline-event">
        <h5>2015: Заснування компанії</h5>
        <p class="text-justify">Finance Fusion була заснована у 2015 році групою ентузіастів у галузі фінансів та IT.
          Ідея створення платформи виникла з бажання спростити процес управління особистими фінансами та зробити його
          доступним для всіх. Перші розробки включали базові інструменти для відстеження доходів та витрат, а також
          простий інтерфейс користувача. Перші роки роботи були спрямовані на те, щоб зрозуміти потреби користувачів і
          створити продукт, який би задовольняв їхні запити. Ми проводили багато зустрічей з потенційними користувачами,
          збирали їхні відгуки та вдосконалювали нашу платформу.</p>
      </div>
      <div class="timeline-event">
        <h5>2017: Впровадження мобільного додатку</h5>
        <p class="text-justify">У 2017 році ми запустили наш перший мобільний додаток для платформ Android та iOS. Це
          дозволило користувачам мати доступ до своїх фінансів у будь-який час та у будь-якому місці. Мобільний додаток
          включав функції для швидкого введення витрат, перегляду балансу рахунків та отримання сповіщень про фінансові
          події. Завдяки мобільному додатку ми значно розширили нашу аудиторію. Користувачі оцінили зручність мобільного
          доступу до своїх фінансових даних, що дозволило їм краще контролювати свої витрати навіть у дорозі.</p>
      </div>
      <div class="timeline-event">
        <h5>2018: Інтеграція з банківськими рахунками</h5>
        <p class="text-justify">У 2018 році ми здійснили інтеграцію з банківськими рахунками, що дозволило автоматично
          аналізувати транзакції користувачів. Це значно спростило відстеження доходів та витрат, адже тепер вводити
          дані вручну. Інтеграція дозволила зберігати час та мінімізувати помилки при введенні даних. Ми також
          впровадили функцію автоматичних звітів, які генеруються на основі банківських транзакцій. Користувачі можуть
          отримувати детальні звіти про свої фінанси, що допомагає їм краще планувати бюджет та
          аналізувати фінансові звички.</p>
      </div>
      <div class="timeline-event">
        <h5>2020: Розширення функціоналу</h5>
        <p class="text-justify">У 2020 році ми додали інструменти для інвестиційного аналізу. Це дозволило користувачам
          приймати більш обґрунтовані фінансові рішення щодо своїх інвестицій. Новий функціонал включав можливість
          аналізу портфеля інвестицій, прогнозування доходності та оцінки ризиків. Ми також запровадили функцію
          порівняння інвестиційних продуктів, що допомагає користувачам вибрати найбільш вигідні варіанти для
          інвестування. Завдяки цьому, наша платформа стала не лише інструментом для управління витратами, але й
          помічником у світі інвестицій.</p>
      </div>
      <div class="timeline-event">
        <h5>2023: Мільйон користувачів</h5>
        <p class="text-justify">У 2023 році ми досягли позначки у мільйон користувачів по всьому світу. Це підтвердило
          популярність та ефективність нашої платформи. Ми продовжували розширювати наші сервіси, додаючи нові функції
          та покращуючи існуючі, щоб забезпечити максимальну зручність для наших користувачів. Ми також розширили нашу
          присутність на міжнародному ринку, відкривши офіси у кількох нових країнах та локалізувавши нашу платформу для
          різних мов. Це дозволило нам краще розуміти потреби користувачів з різних регіонів та адаптувати наші послуги
          під їхні вимоги.</p>
      </div>
    </div>
  </div>

  <div class="container mt-3 mt-md-5 mb-5">
    <h2 class="text-center mb-4">Команда</h2>
    <div class="row">
      <div class="col-md-6 mb-3">
        <div class="card custom-card h-100">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-start mb-3">
              <img src="{% static 'pages/img/team/oleksandr_ivanenko.jpg' %}" alt="Oleksandr Ivanenko" class="rounded-circle me-3"
                width="50" height="50">
              <div>
                <h5 class="mb-0">Олександр Іваненко</h5>
                <p class="mb-0">Генеральний директор (CEO)</p>
              </div>
            </div>
            <p class="card-text text-justify">Має понад 15 років досвіду у сфері фінансів та управління бізнесом.
              Займається стратегічним плануванням та розвитком компанії.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 mb-3">
        <div class="card custom-card h-100">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-start mb-3">
              <img src="{% static 'pages/img/team/natalia_kovalchuk.jpg' %}" alt="Natalia Kovalchuk" class="rounded-circle me-3"
                width="50" height="50">
              <div>
                <h5 class="mb-0">Наталія Ковальчук</h5>
                <p class="mb-0">Головний фінансовий директор (CFO)</p>
              </div>
            </div>
            <p class="card-text text-justify">Експерт у фінансовому аналізі та плануванні, з багаторічним досвідом
              роботи у банківській сфері.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 mb-3 mb-md-0 mt-0 mt-md-3">
        <div class="card custom-card h-100">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-start mb-3">
              <img src="{% static 'pages/img/team/andrii_kravchenko.jpg' %}" alt="Andrii Kravchenko" class="rounded-circle me-3"
                width="50" height="50">
              <div>
                <h5 class="mb-0">Андрій Кравченко</h5>
                <p class="mb-0">Технічний директор (CTO)</p>
              </div>
            </div>
            <p class="card-text text-justify">Провідний спеціаліст у галузі програмування та IT-інновацій,
              відповідальний за технічну реалізацію проектів.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 mb-0 mt-0 mt-md-3">
        <div class="card custom-card h-100">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-start mb-3">
              <img src="{% static 'pages/img/team/iryna_lysenko.jpg' %}" alt="Iryna Lysenko" class="rounded-circle me-3" width="50"
                height="50">
              <div>
                <h5 class="mb-0">Ірина Лисенко</h5>
                <p class="mb-0">Маркетинговий директор (CMO)</p>
              </div>
            </div>
            <p class="card-text text-justify">Має великий досвід у сфері маркетингу та реклами, керує просуванням бренду
              Finance Fusion на ринку.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container mt-3 mt-md-5 mb-5">
    <h2 class="text-center mb-4">Наші цінності</h2>
    <div class="row">
      <div class="col-md-6 col-xxl-3 mb-3 mb-md-3 mb-xxl-0">
        <div class="card custom-card d-flex flex-column h-100">
          <div class="card-body text-center pt-4">
            <i class="bi bi-people-fill text-info fs-2 mb-3"></i>
            <h5 class="card-title mt-2 mb-3">Клієнтоорієнтованість</h5>
            <p class="card-text">Ми ставимо потреби наших клієнтів на перше місце і постійно працюємо над покращенням їх
              досвіду користування.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-xxl-3 mb-3 mb-md-3 mb-xxl-0">
        <div class="card custom-card d-flex flex-column h-100">
          <div class="card-body text-center pt-4">
            <i class="bi bi-cpu text-info fs-2 mb-3"></i>
            <h5 class="card-title mt-2 mb-3">Інновації</h5>
            <p class="card-text">Ми постійно шукаємо нові підходи та рішення для забезпечення найкращих фінансових
              інструментів.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-xxl-3 mb-3 mb-md-0 mt-0 mt-md-3 mt-xxl-0">
        <div class="card custom-card d-flex flex-column h-100">
          <div class="card-body text-center pt-4">
            <i class="bi bi-transparency text-info fs-2 mb-3"></i>
            <h5 class="card-title mt-2 mb-3">Прозорість</h5>
            <p class="card-text">Ми надаємо клієнтам повну прозорість у всіх аспектах нашої роботи, щоб забезпечити
              довіру та надійність.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-xxl-3 mb-0 mt-0 mt-md-3 mt-xxl-0">
        <div class="card custom-card d-flex flex-column h-100">
          <div class="card-body text-center pt-4">
            <i class="bi bi-shield-shaded text-info fs-2 mb-3"></i>
            <h5 class="card-title mt-2 mb-3">Безпека</h5>
            <p class="card-text">Ми гарантуємо високий рівень безпеки даних наших користувачів та захист їх особистої
              інформації.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container mt-3 mt-md-5 mb-5">
    <h2 class="text-center mb-4">Партнери</h2>
    <div class="row justify-content-center mx-2">
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/private_bank.png' %}" alt="Privat Bank" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/monobank.png' %}" alt="Monobank" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/softserve.png' %}" alt="SoftServe" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/microsoft.png' %}" alt="Microsoft" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/santander.png' %}" alt="Santander" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/chase_bank.png' %}" alt="Chase Bank" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/deutsche_bank.png' %}" alt="Deutsche Bank" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/bnp_paribas.png' %}" alt="BNP Paribas" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/global_logic.png' %}" alt="GlobalLogic" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/luxoft.png' %}" alt="Luxoft" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/google.png' %}" alt="Google" class="partner-logo">
      </div>
      <div class="col-4 col-md-3 col-lg-2">
        <img src="{% static 'pages/img/partners/oracle.png' %}" alt="Oracle" class="partner-logo ">
      </div>
    </div>
  </div>
{% endblock %}

coursework/pages/templates/pages/contact.html
{% extends 'pages/loyout.html' %}
{% load static %}

{% block title %}Контакти{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/contact/icons.css' %}" rel="stylesheet">
  <script src="{% static 'pages/js/contact/icons.js' %}"></script>
{% endblock %}

{% block contact_active %}active{% endblock %}

{% block content %}
  <div class="content d-flex justify-content-center align-items-center">
    <a href="https://www.facebook.com" class="mx-2 mx-sm-3 mx-lg-4 text-decoration-none icon-link"
      data-bs-toggle="tooltip" data-bs-placement="top" title="Facebook">
      <i class="bi bi-facebook"></i>
    </a>
    <a href="https://www.youtube.com" class="mx-2 mx-sm-3 mx-lg-4 text-decoration-none icon-link"
      data-bs-toggle="tooltip" data-bs-placement="top" title="YouTube">
      <i class="bi bi-youtube"></i>
    </a>
    <a href="https://www.instagram.com" class="mx-2 mx-sm-3 mx-lg-4 text-decoration-none icon-link"
      data-bs-toggle="tooltip" data-bs-placement="top" title="Instagram">
      <i class="bi bi-instagram"></i>
    </a>
    <a href="https://www.twitter.com" class="mx-2 mx-sm-3 mx-lg-4 text-decoration-none icon-link"
      data-bs-toggle="tooltip" data-bs-placement="top" title="Twitter">
      <i class="bi bi-twitter"></i>
    </a>
    <a href="https://t.me/your_channel" class="mx-2 mx-sm-3 mx-lg-4 text-decoration-none icon-link"
      data-bs-toggle="tooltip" data-bs-placement="top" title="Telegram">
      <i class="bi bi-telegram"></i>
    </a>
    <a href="https://www.linkedin.com" class="mx-2 mx-sm-3 mx-lg-4 text-decoration-none icon-link"
      data-bs-toggle="tooltip" data-bs-placement="top" title="LinkedIn">
      <i class="bi bi-linkedin"></i>
    </a>
  </div>
{% endblock %}

coursework/pages/templates/pages/loyout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous" 
  />
  <script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
    crossorigin="anonymous">
  </script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'pages/css/general/navigation_menu.css' %}">
  {% block links %}{% endblock %}
  <link rel="stylesheet" href="{% static 'pages/css/general/footer.css' %}">
</head>
<body class="d-flex flex-column min-vh-100">
  <nav class="navbar navbar-expand-lg navbar-dark custom-nav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main' %}">
        <img src="{% static 'pages/img/logo.png' %}" alt="Logo" width="70" />
      </a>
      <button 
        class="navbar-toggler" 
        type="button" 
        data-bs-toggle="collapse" 
        data-bs-target="#navbarNav"
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% block main_active %}{% endblock %}" aria-current="page" href="{% url 'main' %}">Головна</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block about_us_active %}{% endblock %}" href="{% url 'about_us' %}">Про нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block contact_active %}{% endblock %}" href="{% url 'contact' %}">Контакти</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% block enter_active %}{% endblock %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Вхід
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item {% block sign_up_disabled %}{% endblock %}" href="{% url 'users:sign_up' %}">Зареєструватися</a></li>
              <li><a class="dropdown-item {% block log_in_disabled %}{% endblock %}" href="{% url 'users:log_in' %}">Увійти в аккаунт</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

  <footer class="footer text-center py-3">
    <div class="container">
      <p>&copy; 2024 Finance Fusion. All rights reserved.</p>
      <p>Contact Us: <a href="mailto:support@financefusion.com" class="text-reset">support@financefusion.com</a></p>
      <div class="mt-2 d-flex justify-content-center align-items-center">
        <a href="{% url 'documents' document_id=1 %}" class="me-3">Privacy Policy</a>
        <span class="mx-2">|</span>
        <a href="{% url 'documents' document_id=2 %}" class="ms-3">Terms of Use</a>
      </div>
    </div>
  </footer>
</body>
</html>

coursework/pages/templates/pages/main.html
{% extends 'pages/loyout.html' %}
{% load static %}

{% block title %}Головна{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/general/blue-border_and_card.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/main/bg-company_and_btn-lg.css' %}" rel="stylesheet">
{% endblock %}

{% block main_active %}active{% endblock %}

{% block content %}
<div class="container-fluid header text-center py-5">
  <h1 class="display-4">Finance Fusion</h1>
  <p class="lead">Легко управляйте своїми доходами та витратами</p>
</div>

<div class="container mt-3 mt-md-5 mb-5">
  <div class="row">
    <div class="col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
      <div class="blue-border">
        <h2 class="text-center">Ласкаво Просимо!</h2>
        <p class="text-justify mt-1">
          Наш фінансовий інструмент — ваш надійний помічник у керуванні фінансами. Він допоможе вам ефективно
          відстежувати доходи та витрати, аналізувати фінансову діяльність і планувати бюджет, спрямовуючи вас до
          досягнення фінансових цілей. Наша мета - зробити процес управління фінансами простішим і зручнішим для вас,
          надійно захищаючи ваші фінансові дані та надаючи вам необхідну інформацію для прийняття правильних рішень.
        </p>
        <p class="text-justify mb-0">
          Ми пропонуємо інноваційні рішення для покращення вашого життя. Наш веб-сайт дозволить вам економити час і
          зусилля, фокусуючись на справжньо важливих аспектах вашого життя. Завдяки передовим технологіям і зручному
          інтерфейсу ви швидко зможете керувати своїми фінансами, отримувати рекомендації і планувати майбутні
          витрати.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container mb-4 mb-md-5">
  <h2 class="text-center mb-4">Наші переваги</h2>
  <div class="row">
    <div class="col-md-4 mb-2 mb-md-0 mt-0">
      <div class="card custom-card d-flex flex-column h-100">
        <div class="card-body text-center pt-4">
          <i class="bi bi-clipboard2-data text-success fs-2 mb-3"></i>
          <h5 class="card-title mt-2 mb-3">Легке відстеження витрат та доходів</h5>
          <p class="card-text">Зручний інтерфейс для швидкого та легкого відстеження ваших фінансів.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-2 mb-md-0 mt-md-0 mt-2 mt-md-0">
      <div class="card custom-card d-flex flex-column h-100">
        <div class="card-body text-center pt-4">
          <i class="bi bi-shield-check text-success fs-2 mb-3"></i>
          <h5 class="card-title mt-2 mb-3">Безпечне зберігання даних</h5>
          <p class="card-text">Надійний захист вашої фінансової інформації за допомогою сучасних
            технологій безпеки.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-0 mt-2 mt-md-0">
      <div class="card custom-card d-flex flex-column h-100">
        <div class="card-body text-center pt-4">
          <i class="bi bi-currency-exchange text-success fs-2 mb-3"></i>
          <h5 class="card-title mt-2 mb-3">Підтримка декількох валют</h5>
          <p class="card-text">Можливість ведення обліку у різних валютах для вашої зручності.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="bg-company py-4">
  <div class="container">
    <h2 class="text-center mb-4">Про компанію</h2>
    <p class="text-justify">
      Компанія, що стоїть за створенням веб-додатка Finance Fusion, визнана лідером у фінансовій сфері завдяки своєму
      інноваційному підходу та високоякісним продуктам. Заснована з метою революціонізувати спосіб, яким люди
      управляють своїми фінансами, компанія пропонує широкий спектр послуг і продуктів, спрямованих на полегшення
      фінансового планування та управління.
    </p>
    <p class="text-justify">
      Finance Fusion — це один із ключових проєктів цієї компанії, який відзначається своєю простотою в користуванні
      та високою ефективністю. Завдяки інтегрованому підходу до аналізу доходів та витрат, цей веб-додаток дозволяє
      користувачам з легкістю контролювати свої фінанси, планувати бюджет і досягати фінансових цілей.
    </p>
    <p class="text-justify">
      Призначений для широкого кола користувачів, від приватних осіб до малих бізнесів, Finance Fusion створений з
      урахуванням потреб сучасного споживача. Він дозволяє не лише відстежувати витрати і доходи, але й аналізувати
      їхню структуру, отримувати індивідуальні рекомендації щодо економії та інвестування, що робить його незамінним
      інструментом для досягнення фінансового благополуччя.
    </p>
    <p class="text-justify">
      Завдяки поєднанню новаторських технологій та експертного фінансового аналізу, компанія залишається на передовій
      фінтех-індустрії, надаючи своїм клієнтам найкращі рішення для управління фінансами та досягнення фінансових
      цілей.
    </p>
  </div>
</div>

<div class="container pt-5 mb-3 mb-md-5">
  <h2 class="text-center mb-4">Відгуки наших користувачів</h2>
  <div class="row">
    <div class="col-md-6 mb-2 mb-md-0 mt-0">
      <div class="card custom-card h-100">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between mb-3">
            <img src="{% static 'pages/img/clients/mikhail.jpeg' %}" alt="Михайло" class="rounded-circle" width="50" height="50">
            <div class="text-center">
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-fill text-warning"></i>
              <span class="ms-2">5.0</span>
            </div>
          </div>
          <p class="card-text text-justify">"Finance Fusion - це ідеальний інструмент для тих, хто хоче зберегти
            контроль над своїми фінансами. Завдяки його зручному інтерфейсу та аналітичним можливостям, я тепер можу
            легко планувати свої витрати і вибудовувати стратегію розподілу бюджету та організації фінансів. Відмінний
            додаток!"</p>
          <footer class="blockquote-footer text-end">Михайло</footer>
        </div>
      </div>
    </div>
    <div class="col-md-6 mb-2 mb-md-0 mt-2 mt-md-0">
      <div class="card custom-card h-100">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between mb-3">
            <img src="{% static 'pages/img/clients/anna.jpeg' %}" alt="Анна" class="rounded-circle" width="50" height="50">
            <div class="text-center">
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-fill text-warning"></i>
              <i class="bi bi-star-half text-warning"></i>
              <span class="ms-2">4.5</span>
            </div>
          </div>
          <p class="card-text text-justify">"Неймовірно задоволена, що відкрила для себе Finance Fusion. Цей додаток
            став для мене надійним помічником у керуванні фінансами. За допомогою його аналітичних засобів я
            зрозуміла, де я можу зекономити і як ефективніше розподілити свої доходи. Рекомендую усім, хто цінує свій
            час і гроші!"</p>
          <footer class="blockquote-footer text-end">Анна</footer>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mb-3 mb-md-5 text-center">
  <h2 class="mb-3 mb-md-4">Приєднуйтесь до нас</h2>
  <div class="row justify-content-center">
    <div class="col-lg-3 col-md-4 col-sm-5 col-8 mb-2 px-sm-3">
      <a href="{% url 'users:sign_up' %}" class="btn btn-primary btn-lg btn-md w-100">Зареєструватися</a>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-8 mb-2 px-sm-3 pt-2 pt-sm-0">
      <a href="{% url 'users:log_in' %}" class="btn btn-secondary btn-lg w-100">Увійти в аккаунт</a>
    </div>
  </div>
</div>
{% endblock %}