coursework/coursework/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),            # Головна сторінка та інформаційні сторінки
    path('users/', include('users.urls')),      # Сторінки для користувачів
    path('finance/', include('finance.urls')),  # Фінансові сторінки
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursework/finance/urls.py
from django.urls import path
from . import views 

app_name = 'finance'

urlpatterns = [
    path('accounts/', views.accounts, name='accounts'),
    path('accounts/add/', views.add_account, name='add_account'),
    path('accounts/<int:account_id>/', views.edit_account, name='edit_account'),
    path('accounts/<int:account_id>/delete/', views.delete_account, name='delete_account'),
    path('expenses/', views.expenses, name='expenses'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/<int:expense_id>/', views.edit_expense, name='edit_expense'),
    path('expenses/<int:expense_id>/delete/', views.delete_expense, name='delete_expense'),
    path('income/', views.income, name='income'),
    path('income/add/', views.add_income, name='add_income'),
    path('income/<int:income_id>/', views.edit_income, name='edit_income'),
    path('income/<int:income_id>/delete/', views.delete_income, name='delete_income'),
    path('transaction_history/', views.transaction_history, name='transaction_history'),
    path('new_transaction/', views.new_transaction, name='new_transaction')
]

coursework/pages/urls.py
from django.urls import path
from . import views 


urlpatterns = [
    path('', views.main, name='main'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('documents/<int:document_id>/', views.documents, name='documents'),
]

coursework/users/urls.py
from django.urls import path
from . import views 

app_name = 'users'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_in/', views.log_in, name='log_in'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('log_out/', views.logout_user, name='logout_user'),
]

coursework/finance/models.py
from django.db import models
from django.contrib.auth.models import User
from pages.models import AccountCategory, ExpenseCategory, IncomeCategory

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_name = models.CharField(max_length=100, blank=False, null=False)
    account_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    date_and_time_of_creation = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(AccountCategory, on_delete=models.CASCADE, blank=False, null=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.account_name 
    
    class Meta:
        # unique_together = ('user', 'account_name')

        verbose_name = 'Рахунок'
        verbose_name_plural = 'Рахунки'
    
class ChangeType(models.Model):
    change_name = models.CharField(max_length=50, unique=True, null=False, blank=False)
    icon_name = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.change_name
    
    class Meta:
        verbose_name = 'Назва та іконка зміни в рахунку'
        verbose_name_plural = 'Назви та іконки змін в рахунках'


class AccountHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    date_and_time = models.DateTimeField(auto_now_add=True)
    change_type = models.ForeignKey(ChangeType, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.account} — {self.change_type.change_name}"
    
    class Meta:
        verbose_name = 'Зміна в рахунку'
        verbose_name_plural = 'Зміни в рахунках'

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    from_account = models.ForeignKey(Account, related_name='from_account', on_delete=models.CASCADE)
    to_account = models.ForeignKey(Account, related_name='to_account', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_and_time = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.from_account.account_amount -= self.amount
        self.to_account.account_amount += self.amount
        self.from_account.save()
        self.to_account.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.from_account} -> {self.to_account} — {self.amount}"

    class Meta:
        verbose_name = 'Транзакція'
        verbose_name_plural = 'Транзакції'

class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)
    date_and_time = models.DateTimeField(auto_now_add=False, blank=False, null=False)
    tag = models.CharField(max_length=20, blank=True)
    comment = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.account} - {self.amount} - {self.category}"

    class Meta:
        verbose_name = 'Витрата'
        verbose_name_plural = 'Витрати'

class Income(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    category = models.ForeignKey(IncomeCategory, on_delete=models.CASCADE)
    date_and_time = models.DateTimeField(auto_now_add=False, blank=False, null=False)
    tag = models.CharField(max_length=20, blank=True, null=False)
    comment = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.account} - {self.amount} - {self.category}"

    class Meta:
        verbose_name = 'Дохід'
        verbose_name_plural = 'Доходи'

coursework/finance/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Account, ChangeType, AccountHistory, Transaction, Expense, Income
from .forms import AccountForm, TransactionForm, ExpenseForm, IncomeForm
from itertools import chain
from operator import attrgetter


@login_required
def accounts(request):
    user_accounts = Account.objects.filter(user=request.user, is_active=True).order_by('date_and_time_of_creation')
    total_balance = sum(account.account_amount for account in user_accounts)

    profile = request.user.profile
    currency_initials = profile.currency.initials if profile.currency else ''

    return render(request, 'finance/accounts.html', {'accounts': user_accounts, 'total_balance': total_balance, 
    'currency_initials': currency_initials})

@login_required
def add_account(request):
    if request.method == 'POST':
        form = AccountForm(request.POST, user=request.user)
        if form.is_valid():
            account = form.save(commit=False)
            account.user = request.user
            account.save()

            # Запис у історію
            change_type = ChangeType.objects.get(change_name='Додавання рахунку')
            AccountHistory.objects.create(
                user=request.user,
                account=account,
                change_type=change_type,
                amount=account.account_amount
            )
            return redirect('finance:accounts')
    else:
        form = AccountForm(user=request.user)
    
    return render(request, 'finance/add_account.html', {'form': form})

@login_required
def edit_account(request, account_id):
    account = get_object_or_404(Account, id=account_id, user=request.user, is_active=True)
    if request.method == 'POST':
        old_amount = account.account_amount
        form = AccountForm(request.POST, instance=account, user=request.user)
        if form.is_valid():
            account = form.save()

            # Обчислення різниці між старою та новою сумою
            difference = account.account_amount - old_amount

            # Запис у історію тільки якщо є різниця у сумі
            if difference != 0:
                change_type = ChangeType.objects.get(change_name='Редагування рахунку')
                AccountHistory.objects.create(
                    user=request.user,
                    account=account,
                    change_type=change_type,
                    amount=difference
                )
            return redirect('finance:accounts')
        
    else:
        form = AccountForm(instance=account, user=request.user)

    return render(request, 'finance/edit_account.html', {'form': form, 'account': account})

@login_required
def delete_account(request, account_id):
    account = get_object_or_404(Account, id=account_id, user=request.user, is_active=True)
    if request.method == 'POST':
        account_amount = account.account_amount

        account.is_active = False
        account.save()
        
        # Запис у історію
        change_type = ChangeType.objects.get(change_name='Видалення рахунку')
        AccountHistory.objects.create(
            user=request.user,
            account=account,
            change_type=change_type,
            amount=account_amount
        )
        return redirect('finance:accounts')
    return render(request, 'finance/delete_account.html', {'account': account})

@login_required
def expenses(request):
    user_expenses = Expense.objects.filter(user=request.user).order_by('-date_and_time')
    user_accounts = Account.objects.filter(user=request.user)
    total_balance = sum(account.account_amount for account in user_accounts)

    profile = request.user.profile
    currency_initials = profile.currency.initials if profile.currency else ''

    return render(request, 'finance/expenses.html', {'expenses': user_expenses, 'total_balance': total_balance, 'currency_initials': currency_initials})

@login_required
def add_expense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('finance:expenses')
    else:
        form = ExpenseForm(user=request.user)
    return render(request, 'finance/add_expense.html', {'form': form})

@login_required
def edit_expense(request, expense_id):
    expense = get_object_or_404(Expense, id=expense_id, user=request.user)
    old_amount = expense.amount  # Збережемо стару суму витрат
    if request.method == "POST":
        form = ExpenseForm(request.POST, instance=expense, user=request.user)
        if form.is_valid():
            new_expense = form.save(commit=False)
            new_expense.account.account_amount += old_amount
            new_expense.account.save()
            new_expense.save()
            return redirect('finance:expenses')  # змініть на вашу URL-ім'я для списку витрат
    else:
        initial_data = {
            'date_and_time': expense.date_and_time.strftime('%Y-%m-%dT%H:%M')
        }
        form = ExpenseForm(instance=expense, initial=initial_data, user=request.user)
    return render(request, 'finance/edit_expense.html', {'form': form, 'expense': expense})

@login_required
def delete_expense(request, expense_id):
    expense = get_object_or_404(Expense, id=expense_id, user=request.user)
    if request.method == "POST":
        account = expense.account
        account.account_amount += expense.amount
        account.save()
        expense.delete()
        return redirect('finance:expenses')  # змініть на вашу URL-ім'я для списку витрат
    return render(request, 'finance/delete_expense.html', {'expense': expense})

@login_required
def income(request):
    user_incomes = Income.objects.filter(user=request.user).order_by('-date_and_time')
    user_accounts = Account.objects.filter(user=request.user)
    total_balance = sum(account.account_amount for account in user_accounts)

    profile = request.user.profile
    currency_initials = profile.currency.initials if profile.currency else ''
    
    return render(request, 'finance/income.html', {'incomes': user_incomes, 'total_balance': total_balance, 'currency_initials': currency_initials})

@login_required
def add_income(request):
    if request.method == 'POST':
        form = IncomeForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('finance:income')
    else:
        form = IncomeForm(user=request.user)
    return render(request, 'finance/add_income.html', {'form': form})

@login_required
def edit_income(request, income_id):
    income = get_object_or_404(Income, id=income_id, user=request.user)
    old_amount = income.amount  # Збережемо стару суму доходу
    if request.method == "POST":
        form = IncomeForm(request.POST, instance=income, user=request.user)
        if form.is_valid():
            new_income = form.save(commit=False)
            difference = new_income.amount - old_amount
            new_income.account.account_amount += difference
            new_income.account.save()
            new_income.save()
            return redirect('finance:income')  # змініть на вашу URL-ім'я для списку доходів
    else:
        initial_data = {
            'date_and_time': income.date_and_time.strftime('%Y-%m-%dT%H:%M')
        }
        form = IncomeForm(instance=income, initial=initial_data, user=request.user)
    return render(request, 'finance/edit_income.html', {'form': form, 'income': income})

@login_required
def delete_income(request, income_id):
    income = get_object_or_404(Income, id=income_id, user=request.user)
    if request.method == "POST":
        account = income.account
        account.account_amount -= income.amount
        account.save()
        income.delete()
        return redirect('finance:income')  # змініть на вашу URL-ім'я для списку доходів
    return render(request, 'finance/delete_income.html', {'income': income})

@login_required
def transaction_history(request):
    history = AccountHistory.objects.filter(user=request.user)
    transactions = Transaction.objects.filter(user=request.user)

    # Об'єднуємо записи з обох таблиць
    combined_history = sorted(
        chain(history, transactions),
        key=attrgetter('date_and_time'),
        reverse=True
    )

    profile = request.user.profile
    currency_initials = profile.currency.initials if profile.currency else ''
    
    return render(request, 'finance/transaction_history.html', {'history': combined_history, 'currency_initials': currency_initials})

@login_required
def new_transaction(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST, user=request.user)
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.user = request.user
            transaction.save()

            return redirect('finance:accounts')
    else:
        form = TransactionForm(user=request.user)
    return render(request, 'finance/new_transaction.html', {'form': form})

coursework/finance/templates/finance/accounts.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Рахунки{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/total_balance.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/icon_buttons.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/accounts.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/add_button.css' %}" rel="stylesheet">
{% endblock %}

{% block accounts_active %}active{% endblock %}

{% block content %}
  <div class="container-fluid header text-center py-5">
    <h1 class="display-4">Рахунки</h1>
  </div>

  <div class="container total-balance">
    <span>Загальний баланс</span>
    <span class="total-amount">{{ total_balance }} {{ currency_initials }}</span>
  </div>

  <div class="container icon-buttons">
    <a href="{% url 'finance:transaction_history' %}" class="icon-button">
      <div class="icon">
        <i class="bi bi-clock-history"></i>
      </div>
      <span>Історія транзакцій</span>
    </a>
    <a href="{% url 'finance:new_transaction' %}" class="icon-button">
      <div class="icon">
        <i class="bi bi-plus-circle"></i>
      </div>
      <span>Нова транзакція</span>
    </a>
  </div>

  <div class="container accounts">
    {% for account in accounts %}
      <a href="{% url 'finance:edit_account' account.id %}" class="account-button">
        <div class="account-details">
          <i class="{{ account.category.icon_name }} account-icon"></i>
          <span>{{ account.account_name }}</span>
        </div>
        <span>{{ account.account_amount }} {{ currency_initials }}</span>
      </a>
    {% endfor %}
  </div>

  <a href="{% url 'finance:add_account' %}" class="fab">
    <i class="bi bi-plus"></i>
	</a>
{% endblock %}

coursework/finance/templates/finance/delete_account.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Додати рахунок{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/log_in/log_in.css' %}" rel="stylesheet">
{% endblock %}

{% block accounts_active %}active{% endblock %}

{% block content %}
  <div class="container my-5 main-content">
    <h2 class="mb-3 text-center">Видалити рахунок</h2>
    <div class="row justify-content-center">
      <div class="col-10   col-md-6 col-lg-5 form-container">
        <form method="POST">
            {% csrf_token %}
            <p class="text-center">Ви впевнені, що хочете видалити рахунок "{{ account.account_name }}"?</p>
            <div class="d-grid mt-4">
              <button type="submit" class="btn btn-danger">Видалити</button>
              <a href="{% url 'finance:edit_account' account.id %}" class="btn btn-secondary mt-3">Скасувати</a>
            </div>
          </form>
      </div>
    </div>
  </div>
{% endblock %}

coursework/finance/templates/finance/delete_expense.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Видалити витрату{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/log_in/log_in.css' %}" rel="stylesheet">
{% endblock %}

{% block expenses_active %}active{% endblock %}

{% block content %}
  <div class="container my-5 main-content">
    <h2 class="mb-3 text-center">Видалити витрати</h2>
    <div class="row justify-content-center">
      <div class="col-10 col-md-6 col-lg-5 form-container">
        <form method="POST">
          {% csrf_token %}
          <p class="text-center">Ви впевнені, що хочете видалити витрати "{{ expense }}"?</p>
          <div class="d-grid mt-4">
            <button type="submit" class="btn btn-danger">Видалити</button>
            <a href="{% url 'finance:edit_expense' expense.id %}" class="btn btn-secondary mt-3">Скасувати</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

coursework/finance/templates/finance/delete_income.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Видалити дохід{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/log_in/log_in.css' %}" rel="stylesheet">
{% endblock %}

{% block expenses_active %}active{% endblock %}

{% block content %}
  <div class="container my-5 main-content">
    <h2 class="mb-3 text-center">Видалити дохід</h2>
    <div class="row justify-content-center">
      <div class="col-10 col-md-6 col-lg-5 form-container">
        <form method="POST">
          {% csrf_token %}
          <p class="text-center">Ви впевнені, що хочете видалити дохід "{{ income }}"?</p>
          <div class="d-grid mt-4">
            <button type="submit" class="btn btn-danger">Видалити</button>
            <a href="{% url 'finance:edit_income' income.id %}" class="btn btn-secondary mt-3">Скасувати</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

coursework/finance/templates/finance/edit_account.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Редагувати рахунок{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'pages/css/log_in/log_in.css' %}" rel="stylesheet">
{% endblock %}

{% block accounts_active %}active{% endblock %}

{% block content %}
  <div class="container my-5 main-content">
    <h2 class="mb-3 text-center">Редагувати рахунок</h2>
    <div class="row justify-content-center">
      <div class="col-md-7 col-lg-6 form-container">
        <form method="POST" novalidate>
          {% csrf_token %}
          <div class="mb-3">
            <label for="{{ form.account_name.id_for_label }}" class="form-label">Назва рахунку</label>
            {{ form.account_name }}
            {% for error in form.account_name.errors %}
              <div class="error-message text-danger">{{ error }}</div>
            {% endfor %}
          </div>
          <div class="mb-3">
            <label for="{{ form.account_amount.id_for_label }}" class="form-label">Кількість грошей</label>
            {{ form.account_amount }}
            {% for error in form.account_amount.errors %}
              <div class="error-message text-danger">{{ error }}</div>
            {% endfor %}
          </div>
          <div class="mb-3">
            <label for="{{ form.category.id_for_label }}" class="form-label">Категорія рахунку</label>
            {{ form.category }}
            {% for error in form.category.errors %}
              <div class="error-message text-danger">{{ error }}</div>
            {% endfor %}
          </div>
          <div class="d-grid mt-4">
            <div class="row">
              <div class="col">
                <button type="submit" class="btn btn-warning w-100">Редагувати</button>
              </div>
              <div class="col">
                <a href="{% url 'finance:delete_account' account.id %}" class="btn btn-danger w-100">Видалити</a>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

coursework/finance/templates/finance/expenses.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Витрати{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/total_balance.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/expense/expense.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/add_button.css' %}" rel="stylesheet">
{% endblock %}

{% block expenses_active %}active{% endblock %}


{% block content %}
  <div class="container-fluid header text-center py-5">
    <h1 class="display-4">Витрати</h1>
  </div>

  <div class="container total-balance">
    <span>Загальний баланс</span>
    <span class="total-amount">{{ total_balance }} {{ currency_initials }}</span>
  </div>

  <div class="container expense-container">
    <div class="list-group">
      {% for expense in expenses %}
        {% with expense.date_and_time|date:"d-m-Y" as current_date %}
          {% ifchanged current_date %}
            <div class="date-separator">{{ current_date }}</div>
          {% endifchanged %}
        {% endwith %}
        <a href="{% url 'finance:edit_expense' expense.id %}" class="expense-button">
          <div class="list-group-item expense d-flex align-items-center justify-content-between w-100">
            <div class="d-flex align-items-center">
              <i class="expense-icon {{ expense.category.icon_name }}"></i>
              <div class="expense-details">
                <p class="account-name mb-2 mb-sm-3">{{ expense.account.account_name }}</p>
                <p class="tag mb-1">{{ expense.tag }}</p>
                <p class="comment">{{ expense.comment }}</p>
              </div>
            </div>
            <span class="transaction-amount">{{ expense.amount }} {{ currency_initials }}</span>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>

  <a href="{% url 'finance:add_expense' %}" class="fab">
    <i class="bi bi-plus"></i>
  </a>
{% endblock %}

coursework/finance/templates/finance/income.html
{% extends 'finance/loyout_finance.html' %}
{% load static %}

{% block title %}Доходи{% endblock %}

{% block links %}
  <link href="{% static 'pages/css/general/header.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/total_balance.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/expense/expense.css' %}" rel="stylesheet">
  <link href="{% static 'finance/css/accounts/add_button.css' %}" rel="stylesheet">
{% endblock %}

{% block income_active %}active{% endblock %}


{% block content %}
  <div class="container-fluid header text-center py-5">
    <h1 class="display-4">Доходи</h1>
  </div>

  <div class="container total-balance">
    <span>Загальний баланс</span>
    <span class="total-amount">{{ total_balance }} {{ currency_initials }}</span>
  </div>

  <div class="container expense-container">
    <div class="list-group">
      {% for income in incomes %}
        {% with income.date_and_time|date:"d-m-Y" as current_date %}
          {% ifchanged current_date %}
            <div class="date-separator">{{ current_date }}</div>
          {% endifchanged %}
        {% endwith %}
        <a href="{% url 'finance:edit_income' income.id %}" class="expense-button">
          <div class="list-group-item expense d-flex align-items-center justify-content-between w-100">
            <div class="d-flex align-items-center">
              <i class="expense-icon {{ income.category.icon_name }}"></i>
              <div class="expense-details">
                <p class="account-name mb-2 mb-sm-3">{{ income.account.account_name }}</p>
                <p class="tag mb-1">{{ income.tag }}</p>
                <p class="comment">{{ income.comment }}</p>
              </div>
            </div>
            <span class="transaction-amount">{{ income.amount }} {{ currency_initials }}</span>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>

  <a href="{% url 'finance:add_income' %}" class="fab">
    <i class="bi bi-plus"></i>
  </a>
{% endblock %}

coursework/finance/templates/finance/loyout_finance.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous" 
  />
  <script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
    crossorigin="anonymous">
  </script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'pages/css/general/navigation_menu.css' %}">
  {% block links %}{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark custom-nav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'finance:accounts' %}">
        <img src="{% static 'pages/img/logo.png' %}" alt="Logo" width="70" />
      </a>
      <button 
        class="navbar-toggler" 
        type="button" 
        data-bs-toggle="collapse" 
        data-bs-target="#navbarNav"
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% block accounts_active %}{% endblock %}" href="{% url 'finance:accounts' %}">Рахунки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block expenses_active %}{% endblock %}" href="{% url 'finance:expenses' %}">Витрати</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% block income_active %}{% endblock %}" href="{% url 'finance:income' %}">Доходи</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% block profile_active %}{% endblock %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Профіль
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item {% block profile_disabled %}{% endblock %}" href="{% url 'users:view_profile' %}">Профіль користувача</a></li>
              <li><a class="dropdown-item" href="{% url 'users:logout_user' %}">Вийти з аккаунту</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}
</body>

</html>